import type { Metadata } from "next";

import "./globals.css";
import "./blog-highlight.css";
import { ThemeProvider } from "@/providers/theme-provider";

import TargetCursor from "@/components/ui/react.bits/target.cursor";
import { AuthProvider } from "@/providers/auth.provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <Toaster />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <TargetCursor spinDuration={2} hideDefaultCursor={true} />

              {children}
            </AuthProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
