

import "./globals.css";
import "./blog-highlight.css";
import { ThemeProvider } from "@/components/providers/theme-provider";

import { AuthProvider } from "@/components/providers/auth.provider";
import { Toaster } from "sonner";
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <NextTopLoader 
            color="#2563eb" 
            initialPosition={0.08} 
            crawlSpeed={200} 
            height={3} 
            crawl={true} 
            showSpinner={false} 
            easing="ease" 
            speed={200} 
            shadow="0 0 10px #2563eb,0 0 5px #2563eb" 
          />
          <Toaster />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            
            <AuthProvider>
              {children}
            </AuthProvider>
          </ThemeProvider>
        </body>
      </html>
    </>);
}