import type { Metadata } from "next";

import UserFooter from "@/layouts/user/footer";

import UserHeader from "@/layouts/user/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <UserHeader />
      {children}
      <UserFooter />
    </>
  );
}
