

import UserFooter from "@/components/layouts/user/footer";

import UserHeader from "@/components/layouts/user/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children


}) {
  return (
    <>
      <UserHeader />
      {children}
      <UserFooter />
    </>);

}